# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Neckbeard"
license = "BSD-3"
licenselink = "https://github.com/henderjon/neckbeard/blob/master/LICENSE.md"
description = "a very simple and completely blank template for neckbeards and curmudgeons"
homepage = "https://github.com/henderjon/neckbeard"
tags = ["minimal", "simple"]
features = []
min_version = "0.20"

[author]
  name = "henderjon"
  homepage = "https://github.com/henderjon"
